name: kickzo

services:
  signal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: signal
    ports:
      - "${SIGNAL_PORT}:${SIGNAL_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KURENTO_URI: ws://kurento:${KURENTO_PORT}/kurento
    depends_on:
      - kurento
    networks:
      - signal-network

  kurento:
    image: kurento/kurento-media-server:latest
    container_name: kurento
    ports:
      - "${KURENTO_PORT}:${KURENTO_PORT}"
      - "${KMS_MIN_PORT}-${KMS_MAX_PORT}:${KMS_MIN_PORT}-${KMS_MAX_PORT}/udp"
    environment:
      KMS_STUN_IP: stun.l.google.com
      KMS_STUN_PORT: ${KMS_STUN_PORT}
      KMS_TURN_URL: kickzo:kickick@coturn:${COTURN_PORT}
      KMS_MIN_PORT: ${KMS_MIN_PORT}
      KMS_MAX_PORT: ${KMS_MAX_PORT}
    networks:
      - signal-network

  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    command: >
      -n --log-file=stdout
      --min-port=49152 --max-port=65535
      --lt-cred-mech --fingerprint
      --no-multicast-peers --no-cli
      --no-tlsv1 --no-tlsv1_1
      --realm=kurento.local
      --listening-port=3478
      --tls-listening-port=5349
      --relay-ip=0.0.0.0
      --listening-ip=0.0.0.0
      --user=kickzo:kickick
      --verbose
    networks:
      - signal-network

networks:
  signal-network:
    driver: bridge
